version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: music_app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
            - ./docker/.env:/var/www/.env
        command: bash -c "php artisan migrate && php artisan serve --host 0.0.0.0"
        depends_on:
            - "db"

    db:
        image: mariadb:10.5
        container_name: music_app_mysql_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: music_app
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
