version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: music_app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
            - ./docker/.env:/var/www/.env
        command: bash -c "php artisan migrate && php artisan serve --host 0.0.0.0"
        environment:
            DB_HOST: db  # Use the service name as the host
        networks:
            - music-app-net

    db:
        image: mariadb:10.5
        container_name: music_app_mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: music_app
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - music-app-net

    node:
        image: node:16
        container_name: music_app_node
        volumes:
            - .:/var/www
        working_dir: /var/www
        command: bash -c "npm install && npm run dev"
        networks:
            - music-app-net

volumes:
    mysql_data:

networks:
    music-app-net:
        driver: bridge
