version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: music_app
        ports:
            - "8030:8030"
        volumes:
            - .:/var/www
            - .env.docker:/var/www/.env
        command: php artisan serve --host 0.0.0.0 --port=8030
        environment:
            DB_HOST: db  # Use the service name as the host
            DB_PORT: 3306
            DB_DATABASE: music_app
            DB_USERNAME: root
            DB_PASSWORD: root
        networks:
            - laravel-net

    db:
        image: mariadb:10.5
        container_name: music_app_mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: music_app
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel-net

    node:
        image: node:16
        container_name: music_app_node
        volumes:
            - .:/var/www
        working_dir: /var/www
        command: bash -c "npm install && npm run dev"
        networks:
            - laravel-net

volumes:
    mysql_data:

networks:
    laravel-net:
        driver: bridge
